# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 5cdd89f1ac46e8c7bd0f74e30c363fa2efc51e0a31433d77e693850202e71885689be1a483df5b3ca59434cfe338bee655add21927066684bfdc764bba66b4bf

test:
  secret_key_base: c3d3825cf1ff165e93909b082dc2094ab4040efdf3cd0f47f125804ccf07c4433dd61a8ed1eb464f9847d038af8b57a23761fb4ba00af8ff489b334293087028

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
